// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum SessionStatus {
  InLobby,
  Playing
}

enum GameMode {
  Trainning,
  Arena,
  Hardcore
}

enum TeamMode {
  AllInOne,
  TeamFight
}

enum TileType {
  None,
  Grass,
  Block,
  Wall,
  RangeUp,
  SpeedUp,
  BombsUp,
  SpawnA,
  SpawnB,
  SpawnC,
  SpawnD
}

enum EntityType {
  Player,
  Bomb
}

enum Direction {
  Up,
  Left,
  Right,
  Down
}
