// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Map } from "./tables/Map.sol";
import { Session, SessionData } from "./tables/Session.sol";
import { SessionOf } from "./tables/SessionOf.sol";
import { PlayerIndex } from "./tables/PlayerIndex.sol";
import { Position } from "./tables/Position.sol";
import { LastBombPlaced } from "./tables/LastBombPlaced.sol";
import { TileLookup } from "./tables/TileLookup.sol";
import { Bomb } from "./tables/Bomb.sol";
import { DetonateAt } from "./tables/DetonateAt.sol";
import { BombRange } from "./tables/BombRange.sol";
import { PlacedBy } from "./tables/PlacedBy.sol";
import { Player } from "./tables/Player.sol";
import { FireCount } from "./tables/FireCount.sol";
import { BombCount } from "./tables/BombCount.sol";
import { BombUsed } from "./tables/BombUsed.sol";
import { LastBlock } from "./tables/LastBlock.sol";
import { TickCount } from "./tables/TickCount.sol";
