// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Tick } from "./tables/Tick.sol";
import { Map } from "./tables/Map.sol";
import { SessionState, SessionStateData } from "./tables/SessionState.sol";
import { TileLookup } from "./tables/TileLookup.sol";
import { Session } from "./tables/Session.sol";
import { PlayerIndex } from "./tables/PlayerIndex.sol";
import { BombIndex } from "./tables/BombIndex.sol";
import { BombOwner } from "./tables/BombOwner.sol";
import { BombRange } from "./tables/BombRange.sol";
import { Player } from "./tables/Player.sol";
import { Position } from "./tables/Position.sol";
import { LastBombIndex } from "./tables/LastBombIndex.sol";
import { Health } from "./tables/Health.sol";
import { FireCount } from "./tables/FireCount.sol";
import { BombCount } from "./tables/BombCount.sol";
import { BombUsed } from "./tables/BombUsed.sol";
