// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBombSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBombSystem {
  function pepemate__placeBomb() external returns (bytes32 session, uint32 tileX, uint32 tileY);

  function pepemate__triggerBomb(bytes32 session, uint32 tileX, uint32 tileY) external;
}
