// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Entity } from "../../Entity.sol";

/**
 * @title IMatchSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMatchSystem {
  function pepemate__searchMatch(Entity map) external;

  function pepemate__leaveSearch() external;

  function pepemate__settleMatch(Entity mapEntity, address[4] memory players) external;
}
