// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Entity } from "../../Entity.sol";

/**
 * @title IPublicSessionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPublicSessionSystem {
  function pepemate__createPublic(uint256 id, Entity map) external returns (Entity session);

  function pepemate__joinPublic(Entity session, uint8 playerIndex) external;

  function pepemate__leavePublic() external;
}
