// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameMode, TeamMode } from "../common.sol";

/**
 * @title ISessionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISessionSystem {
  function pepemate__createSession(bytes32 id, GameMode gameMode, TeamMode teamMode, bytes32 map) external;

  function pepemate__joinSession(bytes32 session, uint8 playerIndex) external;

  function pepemate__leaveSession() external;
}
