// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IMatchSystem } from "./IMatchSystem.sol";
import { IMovementSystem } from "./IMovementSystem.sol";
import { IPlaceBombSystem } from "./IPlaceBombSystem.sol";
import { IPublicSessionSystem } from "./IPublicSessionSystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";
import { ITriggerBombSystem } from "./ITriggerBombSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IMatchSystem,
  IMovementSystem,
  IPlaceBombSystem,
  IPublicSessionSystem,
  ISpawnSystem,
  ITriggerBombSystem
{}
