import { Animations, Assets } from "../../types";

export const explosionAnimations = [
  {
    key: Animations.ExplosionCenter,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/center/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionUp,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/top/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionDown,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/bottom/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionLeft,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/left/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionRight,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/right/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionHorizontal,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/horizontal/",
    suffix: ".png",
  },
  {
    key: Animations.ExplosionVertical,
    assetKey: Assets.MainAtlas,
    startFrame: 0,
    endFrame: 7,
    frameRate: 24,
    repeat: 0,
    prefix: "sprites/fire/vertical/",
    suffix: ".png",
  },
] as const;
